---
spring:
  profiles: odc
  
server:
  port: 8011

     
eureka:
  instance:
#    hostname: localhost
#    preferIpAddress: false 
    register-with-eureka: false
    fetch-registry: false
 
---
spring:
  profiles: node1
  
---
spring:
  profiles: jvm1
 
---
spring:
  profiles: primary
  application:
    name: eurekacluster
    
server:
  port: 8011
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false 
  client:
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/
    register-with-eureka: true
    fetch-registry: true
    
---
spring:
  profiles: secondary
  application:
    name: eurekacluster
    
server:
  port: 8012
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false 
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
    register-with-eureka: true
    fetch-registry: true