---
server: 
  port: 8081
eureka: 
  client: 
    register-with-eureka: false
---
spring:
  profiles: default
   
zuul:
  ignoredServices: '*'
  routes:
    ms_demo_gateway_v2: /gw/bill/v2/**


VersionConfig: 
  gwName: bill
  gwAcronym: gw
  gwVersion: v2
  gwBaseUrl: http://localhost:8080/
  
---
spring:
  profiles: ui_config_change_to_parallel
  
zuul:
  ignoredServices: '*'
  routes:
    ms_demo_gateway: /gw/bill/v1/**
    ms_demo_gateway_v2: /gw/bill/v2/**

VersionConfig: 
  gwName: bill
  gwAcronym: gw
  gwVersion: v1
  gwBaseUrl: http://localhost:8080/