---
server: 
  port: 8080
eureka: 
  client: 
    register-with-eureka: false

ribbon: 
  ReadTimeout: 10000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
---
spring:
  profiles: odc
    
zuul:
  ignoredServices: '*'
  routes:
    myv_ms_bill_gateway: /gw/bill/v1/**


VersionConfig: 
  gwName: bill
  gwAcronym: gw
  gwVersion: v1
  gwBaseUrl: http://localhost:8080/
---
spring:
  profiles: ui_config_change_to_v2
  
zuul:
  ignoredServices: '*'
  routes:
    myv_ms_bill_gateway_v2: /gw/bill/v1/**
    
VersionConfig: 
  gwName: bill
  gwAcronym: gw
  gwVersion: v1
  gwBaseUrl: http://localhost:8080/

---
spring:
  profiles: node1

---
spring:
  profiles: jvm1

---

spring:
  profiles: ui_redeploy_change_to_v2
  
zuul:
  ignoredServices: '*'
  routes:
    myv_ms_bill_gateway_v2: /gw/bill/v2/**
  
server: 
  port: 8080
eureka: 
  client: 
    register-with-eureka: false
    
VersionConfig: 
  gwName: bill
  gwAcronym: gw
  gwVersion: v2
  gwBaseUrl: http://localhost:8080/
  
---
spring:
  profiles: ui_config_change_to_parallel
  
zuul:
  ignoredServices: '*'
  routes:
    myv_ms_bill_gateway: /gw/bill/v1/**
    myv_ms_bill_gateway_v2: /gw/bill/v2/**

VersionConfig: 
  gwName: bill
  gwAcronym: gw
  gwVersion: v1
  gwBaseUrl: http://localhost:8080/
  gwDistribution : { "enabled" : true,
    "routes": [
        {
            "url": "/gw/bill/",
            "schemes": [
                {
                    "version": "v1",
                    "percent": "50"
                },
                {
                    "version": "v2",
                    "percent": "100"
                }
            ]
        }
    ]
}