---
msBill:
  message: called myv_ms_bill ODC change at pop level
  amount: 150.00
  message_v2: called myv_ms_bill ODC called with one endpoint of V2
  amount_v2: 100.02

---
spring:
  profiles: node1


---
spring:
  profiles: node2

msBill:
  message: called myv_ms_bill ODC node2 change at node level