---
#/ms/profile/v1/hello
server: 
  port: 8085

turbine:
  app-config: myv_ms_bill_gateway
  cluster-config: MY_CLUSTER
  
msBillGateway:
  message: called myv_ms_bill_gateway changed
  
  
ribbon: 
  ReadTimeout: 10000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
---
spring:
  profiles: default

VersionConfig:
  profileBaseUrl: /ms/profile/
  profileServiceName: myv_ms_profile
  profileVersion: v1

  billBaseUrl: /ms/bill/
  billServiceName: myv_ms_bill
  billVersion: v1
  
---
spring:
  profiles: gw_config_change_to_v2

VersionConfig:
  profileServiceName: myv_ms_profile
  profileBaseUrl: /ms/profile/
  profileVersion: v2

  billServiceName: myv_ms_bill
  billVersion: v1
  billBaseUrl: /ms/bill/

---
spring:
  profiles: gw_config_change_to_standalone_v2

VersionConfig:
  profileServiceName: myv_ms_profile_v2
  profileBaseUrl: /ms/profile/
  profileVersion: v2

  billServiceName: myv_ms_bill
  billVersion: v1
  billBaseUrl: /ms/bill/
    
---
spring:
  profiles: gw_config_change_to_parallel
 
VersionConfig:
  profileServiceName: myv_ms_profile
  profileBaseUrl: /ms/profile/
  profileVersion: v1
  profileVersion2: v2
  billServiceName: myv_ms_bill
  billBaseUrl: /ms/bill/
  billVersion: v1
  billVersion2: v2
