---
#server:
#  port: 8092
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8011/eureka/

message: Hello
whomToSayHello: Test message 5

msBill:
  message: called myv_ms_bill
  amount: 140.00
  message_v2: called myv_ms_bill called with one endpoint of V2
  amount_v2: 100.02
  
spring:
  cloud:
    bus:
      trace:
        enabled: true
---
spring:
  profiles: tdc


msBill:
  message: called myv_ms_bill TDC test
  #amount: 140.00

  
---
spring:
  profiles: sdc


msBill:
  message: called myv_ms_bill SDC
  #amount: 160.00

  
---
spring:
  profiles: machine1


msBill:
  #message: called myv_ms_bill_secondInstance v4
  amount: 100.00
  
---
spring:
  profiles: machine2


msBill:
  #message: called myv_ms_bill_secondInstance v4
  amount: 200.00