---
#server:
#  port: 8092
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8011/eureka/

message: Hello
whomToSayHello: Test message 5

msBill:
  message: called myv_ms_bill
  amount: 150.00
  message_v2: called myv_ms_bill called with one endpoint of V2
  amount_v2: 100.02
  
spring:
  cloud:
    bus:
      trace:
        enabled: true
---
spring:
  profiles: sdc


msBill:
  message: called myv_ms_bill SDC
  #amount: 160.00
  message_v2: called myv_ms_bill SDC called with one endpoint of V2
  #amount_v2: 100.02

---
spring:
  profiles: node1

---
spring:
  profiles: jvm1